/**
 * @description Constants for Task object.
 * @author Eugene
 * @date 05.11.2024
**/
public class TaskConstants {

    public static final String SYNC_STATUS_ERROR = 'Error';
    public static final String SYNC_STATUS_IGNORE = 'Ignore';
    public static final String SYNC_STATUS_NEED_SYNC = 'Need Sync';
    public static final String SYNC_STATUS_SYNCED = 'Synced';

    public static final String PRIORITY_NORMAL = 'Normal';
    public static final String PRIORITY_HIGH = 'High';

    public static final String TEAM_RCM = 'RCM';
    public static final String TEAM_PCC = 'PCC';

    public static final String TYPE_TASK = 'Task';

    public static final String QUEUE_OVERRIDE_ELIGIBILITY = 'Eligibility';
}